language: ruby
sudo: false
matrix:
  include:
    - rvm: 2.5.5
    - rvm: 2.6.3
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

os:
  - linux

before_install:
  - gem update --system
  - gem install bundler

script:
  - gem list -l
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
