language: ruby
rvm: ruby-3.0.0-rc1
sudo: false

os:
  - linux

before_install:
  - gem install bundler

script:
  - gem list -l
  - bundle exec rake compile
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
  - gem build ./midori.gemspec

bundler_args: --jobs 1 --retry 3

notifications:
  email: false
